### ISSUE TITLE
Please make an "init_app" method

### ISSUE THREAD

**Issue by AndysonDK** [mrf345/flask_minify#3] opened 2019-06-30 23:38 UTC
So I'm getting these errors when running on the server (not locally)

Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1852, in finalize_request
    response = self.process_response(response)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2131, in process_response
    response = handler(response)
  File "/env/lib/python3.7/site-packages/flask_minify/__init__.py", line 65, in toLoopTag
    request.url_rule.rule in self.bypass
AttributeError: 'NoneType' object has no attribute 'rule'

And I think it's because Flask-Minify extension isn't getting properly registered with the app as all the other extensions are. The extension needs to have an "init_app" method or something like that.

by the way, I'm using blueprints

**Comment by mrf345** [comment] 2019-11-03 23:37
Not sure what can be causing that honestly. Never seen that one before, and missing the factory methods IMO is unlikely the cause, same with blueprints. Anyhow I've added them, plus a fail-safe in-case it's just an edge case. Should be resolved in `0.13` release

**Closed by mrf345** 2019-11-03 23:37 UTC
